application: hub2tweet
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /admin/.*
  script: main.py
  login: admin

- url: .*
  script: main.py
